import '../models/restaurant_model.dart';
import '../models/order_model.dart';
import '../models/menu_item_model.dart';
import '../models/settlement_model.dart';
import '../models/review_model.dart';
import '../models/offer_model.dart';

class DemoData {
  static RestaurantDetails get initialRestaurant => RestaurantDetails(
        id: 'rest_001',
        ownerName: 'Lakshmi Narayana',
        ownerPhone: '9876543210',
        ownerEmail: 'partner@feedofood.com',
        restaurantName: 'FEEDO Biryani & Kitchen Hub',
        restaurantType: 'Cloud Kitchen',
        cuisines: ['Biryani', 'Mughlai', 'North Indian', 'Desserts'],
        address: '84, 100 Feet Rd, HAL 2nd Stage, Indiranagar',
        city: 'Bengaluru',
        state: 'Karnataka',
        pincode: '560038',
        landmark: 'Near Indiranagar Metro Station',
        fssaiNumber: '11223344556677',
        panNumber: 'XXXXXX1234',
        gstNumber: '29ABCDE1234F1Z5',
        bankAccount: '••••••••4321',
        bankName: 'HDFC Bank',
        ifscCode: 'HDFC0001234',
        logoUrl: 'https://images.unsplash.com/photo-1517248135467-4c7edcad34c4?w=200&auto=format&fit=crop&q=80',
        coverUrl: 'https://images.unsplash.com/photo-1555396273-367ea4eb4db5?w=800&auto=format&fit=crop&q=80',
        description: 'Authentic Hyderabadi & Dum Biryanis crafted with fragrant basmati and rich aged spices.',
        rating: 4.8,
        totalReviews: 2450,
        isOnline: true,
        autoAcceptOrders: false,
        newOrderSound: true,
        regStatus: 'APPROVED',
        openingHours: [
          OpeningHour(day: 'Monday', isOpen: true, openTime: '11:00 AM', closeTime: '11:30 PM'),
          OpeningHour(day: 'Tuesday', isOpen: true, openTime: '11:00 AM', closeTime: '11:30 PM'),
          OpeningHour(day: 'Wednesday', isOpen: true, openTime: '11:00 AM', closeTime: '11:30 PM'),
          OpeningHour(day: 'Thursday', isOpen: true, openTime: '11:00 AM', closeTime: '11:30 PM'),
          OpeningHour(day: 'Friday', isOpen: true, openTime: '11:00 AM', closeTime: '12:00 AM'),
          OpeningHour(day: 'Saturday', isOpen: true, openTime: '11:00 AM', closeTime: '12:00 AM'),
          OpeningHour(day: 'Sunday', isOpen: true, openTime: '11:00 AM', closeTime: '12:00 AM'),
        ],
      );

  static List<MenuItemModel> get initialMenuItems => [
        MenuItemModel(
          id: 'item_1',
          name: 'Royal Hyderabadi Dum Biryani',
          description: 'Slow cooked aromatic basmati rice layered with tender spiced marinated pieces and saffron.',
          category: 'Biryani',
          price: 380.0,
          discountPrice: 340.0,
          imageUrl: 'https://images.unsplash.com/photo-1563379091339-03b21ab4a4f8?w=500&auto=format&fit=crop&q=80',
          isVeg: false,
          isAvailable: true,
          preparationTimeMinutes: 20,
          rating: 4.9,
          votes: 680,
          isBestSeller: true,
        ),
        MenuItemModel(
          id: 'item_2',
          name: 'Paneer Butter Masala',
          description: 'Fresh cottage cheese cubes simmered in a velvety rich cashew and tomato butter gravy.',
          category: 'Main Course',
          price: 290.0,
          discountPrice: 260.0,
          imageUrl: 'https://images.unsplash.com/photo-1631452180519-c014fe946bc7?w=500&auto=format&fit=crop&q=80',
          isVeg: true,
          isAvailable: true,
          preparationTimeMinutes: 15,
          rating: 4.7,
          votes: 412,
          isBestSeller: true,
        ),
        MenuItemModel(
          id: 'item_3',
          name: 'Crispy Garlic Chicken Tikka',
          description: 'Succulent boneless chicken chunks marinated in roasted garlic, cream, and tandoori herbs.',
          category: 'Starters',
          price: 320.0,
          imageUrl: 'https://images.unsplash.com/photo-1599488615731-7e5c2823ff28?w=500&auto=format&fit=crop&q=80',
          isVeg: false,
          isAvailable: true,
          preparationTimeMinutes: 18,
          rating: 4.8,
          votes: 310,
        ),
        MenuItemModel(
          id: 'item_4',
          name: 'Butter Garlic Naan',
          description: 'Traditional tandoor-baked leavened flatbread brushed with garlic butter and fresh coriander.',
          category: 'Breads',
          price: 65.0,
          imageUrl: 'https://images.unsplash.com/photo-1601050690597-df0568f70950?w=500&auto=format&fit=crop&q=80',
          isVeg: true,
          isAvailable: true,
          preparationTimeMinutes: 8,
          rating: 4.6,
          votes: 550,
        ),
        MenuItemModel(
          id: 'item_5',
          name: 'Shahi Gulab Jamun (2 Pcs)',
          description: 'Soft milk solids dumplings fried to golden hue and soaked in cardamom rose syrup.',
          category: 'Desserts',
          price: 95.0,
          imageUrl: 'https://images.unsplash.com/photo-1605197148560-643033588266?w=500&auto=format&fit=crop&q=80',
          isVeg: true,
          isAvailable: true,
          preparationTimeMinutes: 5,
          rating: 4.8,
          votes: 280,
        ),
        MenuItemModel(
          id: 'item_6',
          name: 'Mango Lassi Royale',
          description: 'Thick chilled sweet yogurt blended with Alphonso mango pulp and garnished with pistachios.',
          category: 'Beverages',
          price: 110.0,
          imageUrl: 'https://images.unsplash.com/photo-1546173159-315724a31696?w=500&auto=format&fit=crop&q=80',
          isVeg: true,
          isAvailable: true,
          preparationTimeMinutes: 5,
          rating: 4.9,
          votes: 195,
        ),
      ];

  static DeliveryPartner get demoRider => DeliveryPartner(
        id: 'rider_arun',
        name: 'Arun Kumar',
        phoneMasked: '+91 98*** **921',
        vehicleNumber: 'KA 04 EL 9842',
        vehicleModel: 'Hero Splendor Plus',
        rating: 4.9,
        distanceKm: 0.8,
        etaMinutes: 4,
        photoUrl: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150&auto=format&fit=crop&q=80',
        latitude: 12.9716,
        longitude: 77.5946,
      );

  static List<OrderModel> get initialOrders => [
        OrderModel(
          id: 'FD10245',
          customer: CustomerInfo(
            name: 'Priya Sharma',
            phoneMasked: '+91 98*** **452',
            address: 'Flat 402, Sai Residency, 12th Main',
            area: 'Indiranagar',
            distanceKm: 1.8,
            orderCount: 8,
          ),
          items: [
            OrderItem(
              id: 'it1',
              name: 'Royal Hyderabadi Dum Biryani',
              category: 'Biryani',
              price: 340.0,
              quantity: 2,
              isVeg: false,
            ),
            OrderItem(
              id: 'it2',
              name: 'Mango Lassi Royale',
              category: 'Beverages',
              price: 110.0,
              quantity: 2,
              isVeg: true,
            ),
          ],
          subtotal: 900.0,
          deliveryFee: 35.0,
          platformFee: 5.0,
          taxes: 45.0,
          discount: 50.0,
          total: 935.0,
          paymentStatus: 'PAID',
          paymentMethod: 'UPI (GPay)',
          status: 'CREATED',
          deliveryState: 'UNASSIGNED',
          pickupCode: '7284',
          specialInstructions: 'Please include extra mint chutney and onion salad.',
          createdAt: DateTime.now().subtract(const Duration(minutes: 2)).toIso8601String(),
          prepTargetMinutes: 20,
          timeline: [
            OrderTimelineEvent(
              status: 'CREATED',
              title: 'Order Placed',
              description: 'Customer placed order and completed payment',
              time: '2 mins ago',
              completed: true,
              current: true,
            ),
          ],
        ),
        OrderModel(
          id: 'FD10244',
          customer: CustomerInfo(
            name: 'Vikram Mehta',
            phoneMasked: '+91 99*** **810',
            address: 'B-12, Green Glen Layout, Bellandur',
            area: 'Bellandur',
            distanceKm: 3.4,
            orderCount: 3,
          ),
          items: [
            OrderItem(
              id: 'it3',
              name: 'Paneer Butter Masala',
              category: 'Main Course',
              price: 260.0,
              quantity: 1,
              isVeg: true,
            ),
            OrderItem(
              id: 'it4',
              name: 'Butter Garlic Naan',
              category: 'Breads',
              price: 65.0,
              quantity: 3,
              isVeg: true,
            ),
          ],
          subtotal: 455.0,
          taxes: 22.75,
          total: 477.75,
          paymentStatus: 'PAID',
          paymentMethod: 'Credit Card',
          status: 'PREPARING',
          deliveryState: 'RIDER_ASSIGNED',
          pickupCode: '7284',
          rider: demoRider,
          createdAt: DateTime.now().subtract(const Duration(minutes: 12)).toIso8601String(),
          prepStartedAt: DateTime.now().subtract(const Duration(minutes: 8)).toIso8601String(),
          prepMinutes: 10,
          prepTargetMinutes: 15,
          timeline: [
            OrderTimelineEvent(
              status: 'CREATED',
              title: 'Order Placed',
              description: 'Customer placed order',
              time: '12 mins ago',
              completed: true,
            ),
            OrderTimelineEvent(
              status: 'ACCEPTED',
              title: 'Order Accepted',
              description: 'Kitchen acknowledged order',
              time: '10 mins ago',
              completed: true,
            ),
            OrderTimelineEvent(
              status: 'PREPARING',
              title: 'Cooking in Progress',
              description: 'Chef is preparing items',
              time: '8 mins ago',
              completed: true,
              current: true,
            ),
          ],
        ),
        OrderModel(
          id: 'FD10243',
          customer: CustomerInfo(
            name: 'Ananya Deshmukh',
            phoneMasked: '+91 97*** **339',
            address: 'Villa 18, Palm Meadows, Whitefield',
            area: 'Whitefield',
            distanceKm: 5.2,
            orderCount: 14,
          ),
          items: [
            OrderItem(
              id: 'it5',
              name: 'Crispy Garlic Chicken Tikka',
              category: 'Starters',
              price: 320.0,
              quantity: 1,
              isVeg: false,
            ),
            OrderItem(
              id: 'it6',
              name: 'Shahi Gulab Jamun (2 Pcs)',
              category: 'Desserts',
              price: 95.0,
              quantity: 2,
              isVeg: true,
            ),
          ],
          subtotal: 510.0,
          taxes: 25.5,
          total: 535.5,
          paymentStatus: 'PAID',
          paymentMethod: 'UPI (Paytm)',
          status: 'READY_FOR_PICKUP',
          deliveryState: 'RIDER_ARRIVED',
          pickupCode: '7284',
          rider: demoRider,
          packagingDone: true,
          createdAt: DateTime.now().subtract(const Duration(minutes: 25)).toIso8601String(),
          readyAt: DateTime.now().subtract(const Duration(minutes: 3)).toIso8601String(),
          timeline: [
            OrderTimelineEvent(
              status: 'CREATED',
              title: 'Order Placed',
              description: 'Order confirmed',
              time: '25 mins ago',
              completed: true,
            ),
            OrderTimelineEvent(
              status: 'PREPARING',
              title: 'Preparation Completed',
              description: 'Food packaged with safety tape',
              time: '3 mins ago',
              completed: true,
            ),
            OrderTimelineEvent(
              status: 'READY_FOR_PICKUP',
              title: 'Ready & Rider Arrived',
              description: 'Arun Kumar is at pickup bay',
              time: 'Just now',
              completed: true,
              current: true,
            ),
          ],
        ),
      ];

  static List<SettlementModel> get initialSettlements => [
        SettlementModel(
          id: 'set_101',
          date: '28 Sep 2026',
          period: '21 Sep - 27 Sep 2026',
          grossAmount: 48500.0,
          commission: 8730.0,
          taxes: 1571.4,
          netPayout: 38198.6,
          status: 'SETTLED',
          payoutRef: 'HDFC_CMS_9482104921',
        ),
        SettlementModel(
          id: 'set_102',
          date: '21 Sep 2026',
          period: '14 Sep - 20 Sep 2026',
          grossAmount: 42300.0,
          commission: 7614.0,
          taxes: 1370.5,
          netPayout: 33315.5,
          status: 'SETTLED',
          payoutRef: 'HDFC_CMS_8391209381',
        ),
        SettlementModel(
          id: 'set_103',
          date: '30 Sep 2026',
          period: '28 Sep - 30 Sep 2026',
          grossAmount: 14200.0,
          commission: 2556.0,
          taxes: 460.08,
          netPayout: 11183.92,
          status: 'PROCESSING',
          payoutRef: 'Pending Payout Cycle',
        ),
      ];

  static List<ReviewModel> get initialReviews => [
        ReviewModel(
          id: 'rev_1',
          customerName: 'Rahul Verma',
          rating: 5.0,
          date: 'Yesterday',
          comment: 'Biryani was piping hot, basmati grain separation was perfection! Truly restaurant grade.',
          orderedItems: ['Royal Hyderabadi Dum Biryani', 'Mango Lassi Royale'],
          reply: ReviewReply(
            text: 'Thank you so much Rahul! We look forward to cooking for you again.',
            repliedAt: 'Yesterday',
          ),
          tags: ['Hot Food', 'Great Taste', 'Packaging'],
        ),
        ReviewModel(
          id: 'rev_2',
          customerName: 'Sneha Patel',
          rating: 4.5,
          date: '2 days ago',
          comment: 'The paneer butter masala had rich gravy. Delivery was fast and contactless.',
          orderedItems: ['Paneer Butter Masala', 'Butter Garlic Naan'],
          tags: ['Fast Delivery', 'Fresh Paneer'],
        ),
      ];

  static List<OfferModel> get initialOffers => [
        OfferModel(
          id: 'off_1',
          title: 'Flat 20% Off Weekend Feast',
          code: 'FEEDO20',
          type: 'PERCENTAGE',
          discountValue: 20.0,
          maxDiscount: 100.0,
          minOrderValue: 299.0,
          validTill: '31 Oct 2026',
          isActive: true,
          totalRedemptions: 148,
        ),
        OfferModel(
          id: 'off_2',
          title: 'Flat ₹50 Off on orders above ₹199',
          code: 'FIRST50',
          type: 'FLAT',
          discountValue: 50.0,
          minOrderValue: 199.0,
          validTill: '15 Nov 2026',
          isActive: true,
          totalRedemptions: 320,
        ),
      ];
}
